### ISSUE TITLE
margin, padding

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [p-tka4enko/cv-project#16]
Убрать у блоков margin, padding

**Comment by pasha-zolotukhin** [comment]
У всех? А как же тогда задавать отступы между ними?

**Comment by GoodDayTodayOkey** [comment]
Можно, у тебя есть wrapper__какой-то элемент, вот на них и задаешь

**Comment by pasha-zolotukhin** [comment]
Хочу еще уточнить. Если у блока есть какие-то дефолтные отступы, то можно ли их обнулить? По сути ведь если этого не делать, то верстка может меняться от браузера к браузеру + эти дефолтные значения как бы нарушают тот принцип, что у блока не должно быть margin и padding для внешнего позиционирования.

**Comment by Frolikow** [comment]
Да, есть неплохая практика, обнулять все отступы через универсальный селектор. Как итог у тебя уберутся все дефолтные отступы, и при этом универсальный селектор имеет специфичность 0000, а значит он будет переопределен абсолютно любым правилом, которое ты напишешь.

**Comment by p-tka4enko** [comment]
Где-то читал, что в БЭМ не рекомендуется использовать универспльный селектор и лучше все обнуления делать для каждого блока отдельно. А что на этот счет скажут другие?
